In [3]:
import numpy as np
import pandas as pd

### Q1

In [4]:
np.__version__

'1.23.3'

### Q2

In [6]:
#!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-11 21:49:08--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
R'esolution de raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8003::154, ...
Connexion `a raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connect'e.
requ^ete HTTP transmise, en attente de la r'eponse... 200 OK
Taille : 1475504 (1.4M) [text/plain]
Sauvegarde en : << data.csv >>

data.csv            100%[===================>]   1.41M  --.-KB/s    ds 0.05s   

2022-09-11 21:49:08 (29.2 MB/s) - << data.csv >> sauvegard'e [1475504/1475504]



In [4]:
df = pd.read_csv("data.csv")

In [6]:
df.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [10]:
df.shape[0]
#len(df)

11914

### Q3

In [12]:
df["Make"].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

### Q4

In [17]:
df[df["Make"]=="Audi"]["Model"].nunique()

34

### Q5

In [21]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

### Q6

In [82]:
df["Engine Cylinders"].median()

6.0

In [84]:
df["Engine Cylinders"].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [86]:
df["Engine Cylinders"] = df["Engine Cylinders"].fillna(df["Engine Cylinders"].median())
df["Engine Cylinders"].median()

6.0

### Q7

In [24]:
df2 = df[df["Make"]=="Lotus"][["Engine HP", "Engine Cylinders"]].drop_duplicates()

In [74]:
df2

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [29]:
X = df2.to_numpy()

In [76]:
XTX = (X).dot(X.T)
XTX

array([[ 35737.,  41218.,  41029.,  66182.,  75624.,  52188.,  65229.,
         48589.,  45376.],
       [ 41218.,  47540.,  47322.,  76332.,  87224.,  60192.,  75234.,
         56042.,  52336.],
       [ 41029.,  47322.,  47105.,  75982.,  86824.,  59916.,  74889.,
         55785.,  52096.],
       [ 66182.,  76332.,  75982., 122564., 140048.,  96648., 120798.,
         89982.,  84032.],
       [ 75624.,  87224.,  86824., 140048., 160036., 110436., 138036.,
        102824.,  96024.],
       [ 52188.,  60192.,  59916.,  96648., 110436.,  76212.,  95256.,
         70956.,  66264.],
       [ 65229.,  75234.,  74889., 120798., 138036.,  95256., 119061.,
         88689.,  82824.],
       [ 48589.,  56042.,  55785.,  89982., 102824.,  70956.,  88689.,
         66065.,  61696.],
       [ 45376.,  52336.,  52096.,  84032.,  96024.,  66264.,  82824.,
         61696.,  57616.]])

In [77]:
XTX_inv = np.linalg.pinv(XTX)
XTX_inv

array([[ 7.41311158e-03,  6.30352900e-05,  3.16486196e-04,
         2.19228485e-02, -1.84073632e-02,  1.30205492e-02,
        -4.46756338e-03, -9.82155006e-03, -5.51288465e-03],
       [ 6.30352899e-05,  6.23440031e-07,  2.77557279e-06,
         1.86330297e-04, -1.56170531e-04,  1.10693931e-04,
        -3.78032295e-05, -8.33097374e-05, -4.67234806e-05],
       [ 3.16486196e-04,  2.77557279e-06,  1.35931805e-05,
         9.35865409e-04, -7.85522004e-04,  5.55861352e-04,
        -1.90553580e-04, -4.19111128e-04, -2.35211797e-04],
       [ 2.19228485e-02,  1.86330297e-04,  9.35865409e-04,
         6.48326802e-02, -5.44365677e-02,  3.85057861e-02,
        -1.32121366e-02, -2.90455391e-02, -1.63034422e-02],
       [-1.84073632e-02, -1.56170531e-04, -7.85522004e-04,
        -5.44365677e-02,  4.57084017e-02, -3.23311809e-02,
         1.10940707e-02,  2.43885369e-02,  1.36895619e-02],
       [ 1.30205492e-02,  1.10693931e-04,  5.55861352e-04,
         3.85057861e-02, -3.23311809e-02,  2.286957

In [78]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [79]:
z = XTX.dot(XTX_inv)
w = z.dot(y)
w

array([ 614.18726905,  747.44066855,  742.84572374, 1099.71608343,
       1456.59197396,  886.81881751, 1203.8700094 ,  926.64351614,
        848.52945437])